### ISSUE TITLE
Unknow message

### ISSUE THREAD

**Issue by ys1382** [ClearKeep/ck-ios#207] opened 2023-02-02 02:07 UTC
We get this error too often: "Unknow message". It is misspelled and also not helpful.

1. Fix the spelling
2. Show the error message.
3. Collect errors in the cloud, such as with Firebase (after requesting permission from the user). That way we can see which ones are the most common.

<img width="565" alt="215566720-2c443031-9698-42f9-87f5-c57171994dc7" src="https://user-images.githubusercontent.com/1097496/216213460-85b5faed-6954-4f83-9052-ff519c4a6af5.png">

**Comment by EddieLukeAtmey** [comment] 2023-02-02 02:48
@ys1382 can you provide the step to get this message?

**Comment by ys1382** [comment] 2023-02-07 06:11
It happens at various times. For this screenshot it happened when I clicked on the Google login and my SHA was not added to Firebase.

**Comment by EddieLukeAtmey** [comment] 2023-02-15 10:21
The typo issue has been addressed in the commit `32199c1e219313fe1beeb376f84a4d0db45515d7`
The cause of the message was from backend, so I'll close this for now.

**Closed as completed by EddieLukeAtmey** 2023-02-15 10:21 UTC
Labels: bug, enhancement
